"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

const apiBase = () => `${window.location.protocol}//${window.location.hostname}:8788`;
type Chore={id:number;title:string;icon:string;points:number;requires_approval:number;assigned_to:string};
type History={id:number;title:string;icon:string;points:number;status:"pending"|"awarded"|"rejected";completed_at:string;member:string};
type Reward={title:string;emoji:string;target_value:number;unit_label:string;earned:number;remaining:number;percent:number}|null;
type Child={id:number;name:string;avatar:string;grade:number|null;chores:Chore[];history:History[];reward:Reward};
type EventItem={id:string|number;title:string;event_date:string;event_time?:string|null;location?:string|null;member?:string|null};
type Departure={expected_departure:string;aimed_departure?:string|null;destination:string;line:string;platform:string;realtime:boolean};
type Transport={ok?:boolean|null;status:string;stop:string;updated_at?:string|null;stale?:boolean;departures:Departure[]};
type Dashboard={date:string;generated_at:string;children:Child[];approval_queue:History[];review_queue:History[];events:EventItem[];spond_events:EventItem[];activities:Array<{id:number;name:string;location?:string|null;schedule?:string|null;member?:string|null}>;week_plans:Array<{id:number;member:string;summary:string;week_number?:number;year?:number}>;week_plan_days:Array<{id:number;week_plan_id:number;member:string;day:string;date?:string|null;subject?:string|null;note?:string|null;homework?:string|null;bring?:string|null}>;school_calendar:Array<{id:number;name:string;start_date:string;end_date:string}>;weather:{status:string;updated_at?:string|null};transport:Transport;sources:{email:{latest_processed?:string|null;waiting:number};spond:{checked_at?:string|null;ok?:boolean|null};health:{ok?:boolean|null}}};
type Page="family"|"child"|"parent";

const icons=["📖","🧹","🍽️","🧺","🪥","🎒","🗑️","🌱","✨","🎵"];
const dateFormat=new Intl.DateTimeFormat("nb-NO",{weekday:"short",day:"numeric",month:"short"});
const timeFormat=new Intl.DateTimeFormat("nb-NO",{hour:"2-digit",minute:"2-digit"});
function asDate(value?:string|null){if(!value)return null;const result=new Date(value.length===10?`${value}T12:00:00`:value.replace(" ","T"));return Number.isNaN(result.getTime())?null:result}
function when(value?:string|null){const parsed=asDate(value);return parsed?`${dateFormat.format(parsed)} · ${timeFormat.format(parsed)}`:"Ikke oppdatert"}
function eventTime(item:EventItem){if(item.event_time)return item.event_time.slice(0,5);const parsed=asDate(item.event_date);return parsed&&item.event_date.includes("T")?timeFormat.format(parsed):"Hele dagen"}
function completionKey(childId:number,choreId:number){
  const webCrypto=globalThis.crypto;
  if(typeof webCrypto?.randomUUID==="function")return `${childId}-${choreId}-${webCrypto.randomUUID()}`;
  if(typeof webCrypto?.getRandomValues==="function"){const bytes=new Uint32Array(4);webCrypto.getRandomValues(bytes);return `${childId}-${choreId}-${Array.from(bytes,value=>value.toString(36)).join("-")}`}
  return `${childId}-${choreId}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

export function FamilyConsole(){
  const [data,setData]=useState<Dashboard|null>(null);const [token,setToken]=useState("");const [parentToken,setParentToken]=useState("");
  const [page,setPage]=useState<Page>(()=>typeof window!=="undefined"&&new URLSearchParams(window.location.search).has("child")?"child":"family");const [childId,setChildId]=useState<number|null>(()=>typeof window!=="undefined"?Number(new URLSearchParams(window.location.search).get("child"))||null:null);const [busy,setBusy]=useState<number|string|null>(null);const [notice,setNotice]=useState("");const [error,setError]=useState("");
  const load=useCallback(async()=>{try{const session=await fetch(`${apiBase()}/api/session`,{cache:"no-store"});if(!session.ok)throw new Error("Datatjenesten svarer ikke.");setToken((await session.json()).token);const response=await fetch(`${apiBase()}/api/dashboard`,{cache:"no-store"});if(!response.ok)throw new Error("Familiedata kunne ikke leses.");setData(await response.json());setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Ukjent feil")}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);const refresh=window.setInterval(()=>{void load()},30_000);return()=>{window.clearTimeout(timer);window.clearInterval(refresh)}},[load]);
  const child=useMemo(()=>data?.children.find(item=>item.id===childId)||null,[data,childId]);
  async function mutate(path:string,method:string,body?:unknown,parent=false){const response=await fetch(`${apiBase()}${path}`,{method,headers:{"Content-Type":"application/json","X-FamilyBot-Local-Token":token,...(parent?{"X-FamilyBot-Parent-Token":parentToken}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||"Endringen kunne ikke lagres.");return result}
  function openFamily(){history.replaceState(null,"","/");setPage("family");setChildId(null);setNotice("")}
  function openChild(id:number){history.replaceState(null,"",`/?child=${id}`);setChildId(id);setPage("child");setNotice("");window.scrollTo(0,0)}
  async function complete(chore:Chore){if(!child||busy)return;setBusy(chore.id);try{await mutate(`/api/chores/${chore.id}/complete`,"POST",{member_id:child.id,idempotency_key:completionKey(child.id,chore.id)});setNotice(`Ferdig! ${chore.points} poeng er lagt til ⭐`);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Kunne ikke registrere.")}finally{setBusy(null)}}
  async function unlock(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("pin");try{const form=new FormData(event.currentTarget);const result=await mutate("/api/parent/session","POST",{pin:form.get("pin")});setParentToken(result.parent_token);setNotice("Foreldremodus er låst opp.")}catch(cause){setError(cause instanceof Error?cause.message:"Feil kode.")}finally{setBusy(null)}}
  async function addChore(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("add");const element=event.currentTarget;const form=new FormData(element);try{await mutate("/api/chores","POST",{title:form.get("title"),assigned_to:form.get("assigned_to"),icon:form.get("icon"),points:Number(form.get("points")),requires_approval:form.get("requires_approval")==="on"},true);element.reset();setNotice("Oppdraget er klart på barnets side.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Kunne ikke legge til.")}finally{setBusy(null)}}
  async function decide(id:number,decision:"awarded"|"rejected"){setBusy(`approval-${id}`);try{await mutate(`/api/completions/${id}`,"PATCH",{decision},true);setNotice(decision==="awarded"?"Poengene er godkjent.":"Oppdraget er sendt tilbake.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Kunne ikke lagre.")}finally{setBusy(null)}}
  async function archive(id:number){setBusy(`archive-${id}`);try{await mutate(`/api/chores/${id}`,"DELETE",undefined,true);setNotice("Oppdraget er fjernet.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Kunne ikke fjerne.")}finally{setBusy(null)}}
  async function reward(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("reward");const form=new FormData(event.currentTarget);try{await mutate("/api/rewards","POST",{member_id:Number(form.get("member_id")),title:form.get("title"),emoji:form.get("emoji"),goal_type:"points",target_value:Number(form.get("target_value")),unit_label:"poeng"},true);setNotice("Nytt belønningsmål er satt.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Kunne ikke lagre.")}finally{setBusy(null)}}

  if(!data)return <main className="loading"><div className="spinner"/><h1>Familieportalen våkner …</h1>{error&&<p className="error-text">{error}</p>}<button onClick={()=>void load()}>Prøv igjen</button></main>;
  return <main className={`app page-${page}`}>
    <header className="topbar"><button className="brand" onClick={openFamily}><span>F</span><strong>Familieportalen</strong></button><nav aria-label="Hovedmeny"><button className={page==="family"?"active":""} onClick={openFamily}>I dag</button>{data.children.map(item=><button key={item.id} className={childId===item.id?"active":""} onClick={()=>openChild(item.id)}>{item.avatar} {item.name}</button>)}<button className={page==="parent"?"active":""} onClick={()=>{history.replaceState(null,"","/");setPage("parent");setChildId(null)}}>Foreldre</button></nav></header>
    {error&&<div className="toast error" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="toast success" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {page==="family"&&<FamilyHome data={data} openChild={openChild}/>}
    {page==="child"&&child&&<ChildPage child={child} data={data} busy={busy} complete={complete}/>}
    {page==="parent"&&<ParentPage data={data} unlocked={Boolean(parentToken)} busy={busy} unlock={unlock} addChore={addChore} decide={decide} archive={archive} reward={reward}/>}
  </main>
}

function FamilyHome({data,openChild}:{data:Dashboard;openChild:(id:number)=>void}){
  const today=eventsFor(data);const nextSchool=data.school_calendar.find(item=>item.end_date>=data.date);const botHealthy=data.sources.health.ok===true;
  return <>
    <section className="family-hero"><div><p className="eyebrow">Familiens oversikt</p><h1>God morgen.</h1><p>{new Intl.DateTimeFormat("nb-NO",{weekday:"long",day:"numeric",month:"long"}).format(asDate(data.date)!)}</p></div><div className="hero-status"><span className={botHealthy?"live-dot":"stop-dot"}/><div><strong>{botHealthy?"Familiebot fungerer":"Familiebot har stoppet"}</strong><small>Sist oppdatert {when(data.generated_at)}</small></div></div></section>
    <section className="overview-grid" aria-label="Dagens viktigste informasjon">
      <article className="overview-card important"><header><span>📅</span><div><p className="eyebrow">I dag</p><h2>Viktigst nå</h2></div></header><div className="timeline">{today.map(item=><div key={`${item.id}-${item.title}`}><time>{eventTime(item)}</time><div><strong>{item.title}</strong><small>{item.member||"Familien"}{item.location?` · ${item.location}`:""}</small></div></div>)}{today.length===0&&<p className="empty-text">Ingen særskilte avtaler registrert i dag.</p>}</div>{nextSchool&&<div className="info-strip"><strong>{nextSchool.name}</strong><span>{dateFormat.format(asDate(nextSchool.start_date)!)}</span></div>}</article>
      <article className="overview-card"><header><span>🌦️</span><div><p className="eyebrow">Ute</p><h2>Vær og T-bane</h2></div></header><div className="big-status">{data.weather.status}</div><small>Værkilde {when(data.weather.updated_at)}</small><TransportCountdown transport={data.transport}/></article>
      <article className="overview-card"><header><span>🎒</span><div><p className="eyebrow">Skole og fritid</p><h2>Aktiviteter</h2></div></header><div className="compact-list">{data.activities.slice(0,5).map(item=><div key={item.id}><span>{item.member?.slice(0,1)||"F"}</span><div><strong>{item.name}</strong><small>{item.member}{item.schedule?` · ${item.schedule}`:" · Tid kommer"}</small></div></div>)}{data.activities.length===0&&<p className="empty-text">Ingen faste aktiviteter registrert.</p>}</div></article>
      <article className="overview-card"><header><span>🏡</span><div><p className="eyebrow">Hjemme</p><h2>FamilyBot</h2></div></header><div className="service-row"><span className={data.sources.spond.ok===false?"warn-dot":"live-dot"}/><div><strong>Spond</strong><small>{when(data.sources.spond.checked_at)}</small></div></div><div className="service-row"><span className="live-dot"/><div><strong>Skolemail</strong><small>{data.sources.email.waiting||0} venter · {when(data.sources.email.latest_processed)}</small></div></div><p className="bot-copy">FamilyBot samler status fra familiens tjenester.</p></article>
    </section>
    <section className="family-members"><div className="section-heading"><div><p className="eyebrow">Barnas sider</p><h2>Oppdrag og belønning</h2></div><p>Ett trykk til egen side</p></div><div className="account-grid">{data.children.map(child=><button key={child.id} className="child-account" onClick={()=>openChild(child.id)}><span className="account-avatar">{child.avatar}</span><div><strong>{child.name}</strong><small>{child.chores.length?`${child.chores.length} oppdrag igjen`:"Ingen oppdrag ennå"}</small></div>{child.reward&&<div className="mini-balance"><strong>{child.reward.earned} / {child.reward.target_value}</strong><span>{child.reward.emoji} {child.reward.title}</span><div><i style={{width:`${child.reward.percent}%`}}/></div></div>}<b>→</b></button>)}</div></section>
  </>
}

function TransportCountdown({transport}:{transport:Transport}){
  const [now,setNow]=useState(()=>Date.now());
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1_000);return()=>window.clearInterval(timer)},[]);
  const upcoming=transport.departures.filter(item=>{const departure=asDate(item.expected_departure);return departure&&departure.getTime()>now-30_000});
  const next=upcoming[0];
  const seconds=next?Math.max(0,Math.ceil((asDate(next.expected_departure)!.getTime()-now)/1_000)):null;
  const countdown=seconds===null?null:seconds<60?`${seconds} sek`:seconds<3_600?`${Math.floor(seconds/60)} min ${String(seconds%60).padStart(2,"0")} sek`:`${Math.floor(seconds/3_600)} t ${Math.floor(seconds%3_600/60)} min`;
  return <div className="transport-line"><span>🚇</span><div className="departure-board"><div className="departure-heading"><span>{transport.status}</span>{next?.realtime&&<small className="realtime-badge">sanntid</small>}</div>{next&&countdown?<><strong className="departure-countdown" aria-live="off">{countdown}</strong><span className="departure-destination"><b>Linje {next.line}</b> til {next.destination} · spor {next.platform}</span><div className="following-departures" aria-label="Senere avganger">{upcoming.slice(1,4).map(item=><span key={item.expected_departure}><b>{timeFormat.format(asDate(item.expected_departure)!)}</b> {item.destination}</span>)}</div></>:<strong className="departure-unavailable">{transport.stale?"Ingen ferske avganger akkurat nå":"Ingen avganger funnet"}</strong>}<small>{transport.stop} · {transport.stale?"sist lagrede data":"oppdatert"} {when(transport.updated_at)}</small></div></div>
}

function ChildPage({child,data,busy,complete}:{child:Child;data:Dashboard;busy:number|string|null;complete:(chore:Chore)=>Promise<void>}){
  return <><section className="kid-hero"><div className="kid-name"><span>{child.avatar}</span><div><p className="eyebrow">Min side</p><h1>{child.name}</h1></div></div>{child.reward?<div className="reward-card"><div className="reward-top"><div><span>Jeg samler til</span><h2>{child.reward.emoji} {child.reward.title}</h2></div><strong>{child.reward.percent}%</strong></div><div className="progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={child.reward.target_value} aria-valuenow={child.reward.earned}><i style={{width:`${child.reward.percent}%`}}/></div><div className="reward-copy"><strong>{child.reward.earned} / {child.reward.target_value} {child.reward.unit_label}</strong><span>{child.reward.remaining?`${child.reward.remaining} ${child.reward.unit_label} igjen → ${child.reward.title} 🎯`:"Målet er nådd! 🎉"}</span></div></div>:<div className="reward-card"><h2>🎯 Velg et mål sammen</h2></div>}</section><WeekPlan data={data} child={child}/>
  <section className="missions"><div className="section-heading"><div><p className="eyebrow">Mine oppdrag</p><h2>Hva vil du gjøre?</h2></div><span className="count-badge">{child.chores.length} igjen</span></div><div className="mission-grid">{child.chores.map(chore=><button key={chore.id} className="mission-card" disabled={busy!==null} onClick={()=>void complete(chore)}><span className="mission-icon">{chore.icon}</span><span className="mission-title"><strong>{chore.title}</strong><small>{chore.requires_approval?"En voksen godkjenner":"Trykk når du er ferdig"}</small></span><span className="points">+{chore.points}<small>poeng</small></span><span className="done">{busy===chore.id?"Lagrer …":"Ferdig ✓"}</span></button>)}{child.chores.length===0&&<div className="all-done"><span>✨</span><h3>Klar for nye oppdrag!</h3><p>Lag de første oppdragene sammen i foreldresiden.</p></div>}</div></section>
  <section className="child-lower"><article className="history-card"><p className="eyebrow">Min historie</p><h2>Dette har jeg gjort</h2><div className="history-list">{child.history.map(item=><div key={item.id}><span>{item.icon||"✨"}</span><div><strong>{item.title}</strong><small>{when(item.completed_at)}</small></div><b className={item.status}>{item.status==="rejected"?"Prøv igjen":`+${item.points}`}</b></div>)}{!child.history.length&&<p className="empty-text">De første fullførte oppdragene vises her.</p>}</div></article><Glance data={data} child={child}/></section></>
}

function ParentPage({data,unlocked,busy,unlock,addChore,decide,archive,reward}:{data:Dashboard;unlocked:boolean;busy:number|string|null;unlock:(event:FormEvent<HTMLFormElement>)=>Promise<void>;addChore:(event:FormEvent<HTMLFormElement>)=>Promise<void>;decide:(id:number,decision:"awarded"|"rejected")=>Promise<void>;archive:(id:number)=>Promise<void>;reward:(event:FormEvent<HTMLFormElement>)=>Promise<void>}){
  return <section className="parent-shell"><div className="parent-heading"><div><p className="eyebrow">Foreldremodus</p><h1>Oppsett og godkjenning</h1></div><span>🔐 Kun voksne</span></div>{!unlocked?<form className="pin-form" onSubmit={unlock}><label>Foreldrekode<input name="pin" type="password" inputMode="numeric" pattern="[0-9]*" required/></label><button disabled={busy==="pin"}>Lås opp</button></form>:<div className="parent-grid">
    <form className="parent-card" onSubmit={addChore}><p className="eyebrow">Nytt oppdrag</p><h2>Legg til gjøremål</h2><label>Hva skal gjøres?<input name="title" required maxLength={160} placeholder="Pakke gymtøy"/></label><div className="form-row"><label>Barn<select name="assigned_to">{data.children.map(item=><option key={item.id} value={item.name.toLowerCase()}>{item.name}</option>)}</select></label><label>Poeng<input name="points" type="number" min="0" max="1000" defaultValue="5" required/></label></div><fieldset><legend>Ikon</legend><div className="icon-picker">{icons.map((icon,index)=><label key={icon}><input type="radio" name="icon" value={icon} defaultChecked={index===0}/><span>{icon}</span></label>)}</div></fieldset><label className="check"><input name="requires_approval" type="checkbox"/><span>Krever godkjenning</span></label><button className="primary" disabled={busy==="add"}>Legg til oppdrag</button></form>
    <article className="parent-card"><p className="eyebrow">Voksenkontroll</p><h2>Nylig registrert</h2><p className="parent-help">Barna får progresjon med en gang. Underkjenn hvis oppgaven ikke faktisk er gjort; da trekkes poengene og oppgaven åpnes igjen.</p><div className="approval-list">{data.review_queue.map(item=><div key={item.id}><div><strong>{item.icon} {item.title}</strong><span>{item.member} · {item.points} poeng · {item.status==="pending"?"bør kontrolleres":"registrert"}</span></div><div>{item.status==="pending"&&<button onClick={()=>void decide(item.id,"awarded")}>Godkjenn</button>}<button className="quiet reject" onClick={()=>void decide(item.id,"rejected")}>Underkjenn</button></div></div>)}{!data.review_queue.length&&<p className="empty-text">Ingen fullføringer er registrert ennå.</p>}</div></article>
    <form className="parent-card" onSubmit={reward}><p className="eyebrow">Belønning</p><h2>Sett nytt mål</h2><label>Barn<select name="member_id">{data.children.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="form-row reward-input"><label>Emoji<input name="emoji" defaultValue="🎯" maxLength={12}/></label><label>Belønning<input name="title" required placeholder="Kinokveld"/></label></div><label>Poengmål<input name="target_value" type="number" min="1" defaultValue="30" required/></label><button className="primary">Start nytt mål</button></form>
    <article className="parent-card"><p className="eyebrow">Aktive oppdrag</p><h2>Administrer</h2><div className="manage-list">{data.children.flatMap(child=>child.chores.map(chore=><div key={chore.id}><span>{chore.icon}</span><div><strong>{chore.title}</strong><small>{child.name} · {chore.points} poeng</small></div><button onClick={()=>void archive(chore.id)}>Fjern</button></div>))}</div></article>
  </div>}</section>
}

function Glance({data,child}:{data:Dashboard;child:Child}){const today=eventsFor(data,child);const activities=data.activities.filter(item=>item.member===child.name);return <article className="glance-card"><p className="eyebrow">Min dag</p><h2>Skole og aktivitet</h2>{today.map(item=><div className="glance-item" key={`${item.id}-${item.title}`}><strong>{eventTime(item)} · {item.title}</strong><small>{item.location||"I dag"}</small></div>)}{!today.length&&<p className="empty-text">Ingen særskilte avtaler i dag.</p>}{activities.slice(0,3).map(item=><div className="glance-item" key={item.id}><strong>{item.name}</strong><small>{item.schedule||"Tid kommer"}</small></div>)}</article>}
function WeekPlan({data,child}:{data:Dashboard;child:Child}){const plan=data.week_plans.find(item=>item.member===child.name);const days=data.week_plan_days.filter(item=>item.member===child.name);return <section className="week-plan"><div className="section-heading"><div><p className="eyebrow">Skolen denne uken</p><h2>Ukeplan</h2></div>{plan&&<span className="week-badge">Uke {plan.week_number}</span>}</div>{plan?<><p className="week-summary">{plan.summary}</p><div className="week-items">{days.map(item=><article key={item.id}><div><span>{item.day}</span>{item.date&&<time>{dateFormat.format(asDate(item.date)!)}</time>}</div>{item.subject&&<h3>{item.subject}</h3>}{item.homework&&<p><b>📚 Oppgave:</b> {item.homework}</p>}{item.note&&<p><b>ℹ️ Dette skjer:</b> {item.note}</p>}{item.bring&&<p><b>🎒 Husk:</b> {item.bring}</p>}</article>)}</div></>:<div className="no-week-plan"><span>📭</span><div><strong>Ingen ukeplan er registrert ennå</strong><p>Når skolen sender og FamilyBot har behandlet planen, kommer den hit - separat fra poengoppdragene.</p></div></div>}</section>}
function eventsFor(data:Dashboard,child?:Child){const seen=new Set<string>();return [...data.events,...data.spond_events].filter(item=>{const key=`${item.title}|${item.event_date}|${item.member}`;if(item.event_date.slice(0,10)!==data.date||seen.has(key)||child&&(item.member&&item.member!==child.name))return false;seen.add(key);return true}).slice(0,6)}
